resources:
- name: schedule
  type: time
  source:
    start: 2:00 AM
    stop: 9:00 PM

jobs:
- name: delete-gdpr-tickets
  plan:
  - get: schedule
    trigger: true
  - config:
      container_limits: {}
      image_resource:
        source:
          repository: "((readonly_private_ecr_repo_url))"
          tag: concourse-gdpr-tickets-latest
        type: docker-image
      platform: linux
      run:
        args:
        - -xce
        - |
          cd /usr/src/app
          bundle install
          export ZENDESK_LOG_FILE="zendesk-GDPR-tickets.`date +%Y-%m-%d`"
          bundle exec ruby /usr/src/app/lib/tickets-autom8-able.rb
          aws s3 cp $ZENDESK_LOG_FILE s3://${S3_BUCKET_NAME}/
          export ZENDESK_LOG_FILE="zendesk-GDPR-users.`date +%Y-%m-%d`"
          bundle exec ruby /usr/src/app/lib/user-ids-autom8-able.rb
          aws s3 cp $ZENDESK_LOG_FILE s3://${S3_BUCKET_NAME}/
        path: /bin/bash
      params:
        S3_BUCKET_NAME: ((readonly_private_bucket_name))
        ZENDESK_URL: ((zendesk-url))
        ZENDESK_USER_EMAIL: ((zendesk-email))
        ZENDESK_TOKEN: ((zendesk-token))
    task: run
